### ISSUE TITLE
Session: Recent Developments in Exotic and Unconventional Superconductivity

### ISSUE THREAD

**Issue by ViktoriiaKornich** [virtualscienceforum/virtualscienceforum#498] opened 2022-01-25 18:17 UTC
## Title:

Recent Developments in Exotic and Unconventional Superconductivity

## Organizers
- Viktoriia Kornich (University of Wuerzburg)
- David Moeckli (https://sites.google.com/view/mockli/ ) (Universidade Federal do Rio Grande do Sul)
- Alessio Calzona (University of Wuerzburg)

## Description
Unconventional superconductivity is a rapidly developing field that is of high interest nowadays, because new materials can support new technologies. E.g., p-wave superconductor is a potential host for Majorana fermions. Our conference is about various types of unconventional superconductors and also about exotic superconductivity, namely non-equilibrium superconductivity, superconductivity in flat-band systems. This conference will be interesting for both experimentalists and theoreticians.

## List of potential speakers 

Confirmed speakers:
Kristin Willa (Karlsruhe Institute of Technology)		
Miguel Ugeda (CFM Donostia)	
Sofia Michaela Souliou (Karlsruhe Institute of Technology)
Fahad Mahmood (University of Illinois Urbana-Champaign)
Tero Heikkilä (University of Jyväskylä)
Eugene Demler (ETH Zürich)
Aline Ramires (Paul Scherrer Institut)	
Andrey Chubukov (University of Minnesota)

We also plan for a session of 3-4 contributed talks after the invited talks on both days.

## Preferred date and time slot

Two days: March 30-31
We will have one afternoon session 14:00-18:15 (Berlin time) each day.

**Comment by ViktoriiaKornich** [comment] 2022-01-26 13:30
Can we create a webpage this week? What is the procedure for doing it?

**Comment by akhmerov** [comment] 2022-01-27 13:23
Hey @ViktoriiaKornich sounds good! I'll set up a page that you can extend shortly. This week should be doable.

**Comment by adelatorreduran** [comment] 2022-01-27 20:13
Hi @ViktoriiaKornich, my name is Alberto de la Torre, and I'll be your VSF liaison! As you can see, we have created a non-public draft of the webpage in the Superconducting-workshop branch. 

Please, edit the description and program here:
https://github.com/virtualscienceforum/virtualscienceforum/blob/superconducting-workshop/src/unconventional-superconductivity.md

Can you please include a "Title" image and indicate the target audience? Once the changes are made, we will then merge it into the main branch and publish the page. 

It seems that you have already confirmed your speaker list, and you are planning satellite/contributed talks. If we can suggest, we have seen that panel discussion/ brainstorm sessions have contributed to the event's success. Would you consider adding a slot for something like that?

Additionally, we have also created and tested a registration form for the event and booked the afternoons of March 30-31 for you. Would  you consider pushing back the start of each session to make it more amenable to EST audiences?

Looking forward to helping you organizing this event! Don't hesitate to reach out with any questions.

**Comment by ViktoriiaKornich** [comment] 2022-01-27 21:06
Hi @adelatorreduran , thank you! I will discuss the details with the other organisers and then edit the draft of the webpage. Hopefully, I will do it correctly, but I guess, it will stay as a draft anyway until you confirm it, right?

**Comment by ViktoriiaKornich** [comment] 2022-01-27 21:13
Also, @adelatorreduran , we would like to add registration form for the contributed talks and send it around with an advertisement of the conference, as it is usually done. However, that registration should include abstract of the talk or so. So maybe the question of something like: "Do you want to contribute a talk? If yes, please, provide a title and abstract for your talk" should be added to the general registration to combine those two registrations?

**Comment by adelatorreduran** [comment] 2022-01-27 21:42
> Hi @adelatorreduran , thank you! I will discuss the details with the other organisers and then edit the draft of the webpage. Hopefully, I will do it correctly, but I guess, it will stay as a draft anyway until you confirm it, right?

Yes, that's correct.

>Also, @adelatorreduran , we would like to add registration form for the contributed talks and send it around with an advertisement of the conference, as it is usually done. However, that registration should include abstract of the talk or so. So maybe the question of something like: "Do you want to contribute a talk? If yes, please, provide a title and abstract for your talk" should be added to the general registration to combine those two registrations?

I think it should be possible, but let me talk to @akhmerov to make sure it does not mess with the bot.

**Comment by akhmerov** [comment] 2022-01-27 21:56
Modifying the registration form is technically challenging at the moment. There are other things that would be possible, however before going there I want to bring up another point.

Consider: a typical event can have 200—300 people registering. The topic of the workshop is relatively broad, at least in the way it is formulated right now, so that possibly some 30 out of those few hundred could contribute a talk on the event topic, while there's only place for a couple. It is very hard to ensure a transparent and clear selection under such conditions, and also certainly those that did apply and weren't selected will likely be dissatisfied with the decision.

Additionally, right now the planned event duration is at the upper border of what fits in a single day: you are likely to experience a significant drop in the number of attendees in an event of such length.

Are you sure that you want to make a broad call for contributed talks?

**Comment by ViktoriiaKornich** [comment] 2022-01-28 12:03
Thank you for your comment! Certainly, if it is technically challenging, then we will not do it. I will work out all details with the other organisers these days and hopefully we will converge with some version of the webpage soon. Thank you!

**Comment by ViktoriiaKornich** [comment] 2022-01-28 13:03
I honestly did not think that the number of participants would be so high. I thought, the contributed talks would be no more than 8, that's why we planned for 2 hours of 12+3 contributed talks. Bu tif you say that it can be such a big number, than yes, many people would be unhappy. I wonder, how can we then involve young researchers? We have one postdoc among invited speakers, but that is it. I do think involving young researchers in important for any conference. Do you know, what people usually do in such cases, if not a general call for contributed talks?

**Comment by ViktoriiaKornich** [comment] 2022-01-29 16:01
I wonder, will we be able to update our conference website after we publish it? I am not sure, whether we need to ask for the titles of invited talks now or later? So far, we have not asked, so I thought to just put the list of speakers.

**Comment by akhmerov** [comment] 2022-01-30 20:49
> I wonder, will we be able to update our conference website after we publish it?

Absolutely, as many times as you need. At the very least, after the event we remove the registration forms and add video recordings. Your use case of providing an updated program is also perfectly fine.

> Certainly, if it is technically challenging, then we will not do it.

It's not technically challenging—it's rather easy to embed a google form or even ask interested people to send you an email. The main problem, I think, is organizational.

>  Do you know, what people usually do in such cases, if not a general call for contributed talks?

Both the oxides workshop and the Andreev reflection workshop allowed for additional contributions that were made either by sending a video to the conference organizers, or by giving a speakers' corner talk that would be advertised on the workshop page. I think the main difference, though, is the breadth of the topic: in either case there would only be a handful of groups that had works on the workshop topic.

**Comment by ViktoriiaKornich** [comment] 2022-01-30 21:36
Thank you! We have discussed it and decided that we will be sending emails. I have filled in the form that you submitted. The only thing, I did not get how to attach the logo of our conference and also, it seems I created two different documents or "forks". I need only the second one. If you could explain what I should do next?

**Comment by adelatorreduran** [comment] 2022-01-30 22:17
I see [it](https://github.com/ViktoriiaKornich/virtualscienceforum/blob/patch-2/src/unconventional-superconductivity.md). About the photo, you should upload it to virtualscienceforum/src/media and then uncomment and update this line:

 

We are responsible for merging your changes to the main branch. I think we can do that after you upload the conference logo.

**Comment by ViktoriiaKornich** [comment] 2022-01-30 22:57
Thank you! I uploaded pdf file and hopefully uncommented that line (not completely sure because I am not used to this script), but it does not show the logo. Anyway, I saved the changes. If it is ok, please, merge it to the main branch

**Comment by giulia-pacchioni** [comment] 2022-01-31 14:03
> I honestly did not think that the number of participants would be so high. I thought, the contributed talks would be no more than 8, that's why we planned for 2 hours of 12+3 contributed talks. Bu tif you say that it can be such a big number, than yes, many people would be unhappy. I wonder, how can we then involve young researchers? We have one postdoc among invited speakers, but that is it. I do think involving young researchers in important for any conference. Do you know, what people usually do in such cases, if not a general call for contributed talks?

Hi Viktoriia, if I might chime in, I can see why you are keen on offering the option to give a contributed talk to more junior researchers. I think you can consider telling people they can apply for a contribution, which the organizers can decide to accept as either a contributed talk or a 'flash' (2 min) talk or some kind of poster (you can discuss options with your co-organizers). This way if you have too many submissions you can have one of those sessions where several people present their results quickly, without impacting a lot the overall duration of the event but giving visibility to more researchers (and of course you don't have to accept all the talk submissions!)

**Comment by ViktoriiaKornich** [comment] 2022-01-31 14:14
Hi Giulia, thank you! We have discussed it over weekend, and decided that we will send emails to the groups and people who might be interested in presenting their results. Once we settle with the webpage (I really hope somebody will respond to me regarding merging soon), we will start advertising it, sending emails. In parallel, we will ask invited speakers to send us their talks' titles. Thus, we will gradually update our webpage to the full program. This is our plan :-) My main goal for this meeting is to meet/connect to new people and also allow young researchers to have some fresh air, i.e. meet new people and present their results. So we will really try to settle those last sessions well.

**Comment by giulia-pacchioni** [comment] 2022-01-31 14:17
Hi Viktoriia, 

That sounds good! It's good to keep in mind that a virtual event you can have some flexibility with the format, hence you have some nice freedom to arrange things the way you think is best. There is a VSF meeting later today, and I'm sure someone will merge the changes for the webpage in the next few hours.

**Comment by ViktoriiaKornich** [comment] 2022-01-31 14:18
Thank you :-)

**Comment by adelatorreduran** [comment] 2022-01-31 16:20
Hi @ViktoriiaKornich can you make a pull request of your branch? Then we can merge it. Thanks!

**Comment by ViktoriiaKornich** [comment] 2022-01-31 16:21
I will try...

**Comment by akhmerov** [comment] 2022-01-31 17:08
Done; see #499 and the links there. All Viktoriia's changes should be there.

**Comment by adelatorreduran** [comment] 2022-01-31 17:25
Thanks!

**Comment by ViktoriiaKornich** [comment] 2022-02-03 20:15
I put the text for the email to the mailing list, but I have put the wrong link. That link was for the draft webpage. I have only now realised, the one on the VSF website is different. Could you please correct it? I tried to find it, and could not.

**Comment by akhmerov** [comment] 2022-02-03 20:39
This is the workshop page: https://virtualscienceforum.org/unconventional-superconductivity/, and I already fixed it in the email.

**Comment by ViktoriiaKornich** [comment] 2022-02-03 20:40
Thank you, Anton!

**Comment by ViktoriiaKornich** [comment] 2022-02-03 21:24
I wonder, should the speakers also register? Or they should register somehow separately?

**Comment by adelatorreduran** [comment] 2022-02-04 01:23
Oh yeah! It should have mentioned this. Speakers need to register the same way!

**Comment by ViktoriiaKornich** [comment] 2022-02-04 11:13
Sorry, @adelatorreduran , one of our speakers Miguel Ugeda let us know that he cannot make a talk due to schedule conflict he was not aware of before. He suggested Fernando de Juan (Donostia International Physics Center) instead of him, and Fernando has confirmed his participation. So once possible, could you please update the program, i.e. substitute Miguel Ugeda by Fernando de Juan? I would do it myself, but you will need to merge it anyway, so maybe it is faster if you simply past the name and affiliation of Fernando into the file? Thank you!

**Comment by ViktoriiaKornich** [comment] 2022-02-04 12:47
@akhmerov @adelatorreduran sorry, I need to update the webpage. It appeared that due to some emailing failure Amir Yacoby (Harvard University) agreed to present an invited talk, but we did not know about it. So we will now schedule him at 17:05 on March 30. I will apply those changes by myself and also put Fernando de Juan (Donostia International Physics Center), and then ask to merge. I am sorry for troubling you.

**Comment by ViktoriiaKornich** [comment] 2022-02-04 13:20
@akhmerov @adelatorreduran I have introduced all necessary changes and created a pull request. I had to expand the sessions until 18:15 on March 30 and until 18:20 on March 31, I hope it is OK.

**Comment by akhmerov** [comment] 2022-02-04 13:43
All good :heavy_check_mark:

**Comment by ViktoriiaKornich** [comment] 2022-02-04 13:46
Thank you very much!

**Comment by ViktoriiaKornich** [comment] 2022-02-04 15:58
@adelatorreduran I wonder, why I have not received an email from VSF? I used to receive updates from VSF. I am just wondering, if the email was sent or there is a problem?

**Comment by akhmerov** [comment] 2022-02-04 16:07
It seems that Uni-Wuezburg blocks our email provider (mailgun). I'll check whether we can do anything about it, but these decisions are done by local admins, and that's hard for us to fix.

**Comment by ViktoriiaKornich** [comment] 2022-02-04 16:08
I see, this is strange as I have received advertisements from VSF on this email, but it is good that it is just a local problem :-) I will advertise it locally by myself.

**Comment by akhmerov** [comment] 2022-02-04 16:12
Yeah, I see 1543 emails delivered, 44 failed, and out of those most are invalid / deactivated emails.

**Comment by ViktoriiaKornich** [comment] 2022-02-04 16:14
Oh, wow, that is a great number! I think this is way more than I expected for dissemination :-)

**Comment by ViktoriiaKornich** [comment] 2022-02-10 14:15
I am wondering, how many registration are already there? Just to assess our advertisement company :-)

**Comment by akhmerov** [comment] 2022-02-10 14:33
221 — pretty good I think

**Comment by adelatorreduran** [comment] 2022-03-22 05:03
Hi @ViktoriiaKornich, your conference is starting in 9 days! Just wanted to check in. All set from your side? Is there anything I can help with?

**Comment by ViktoriiaKornich** [comment] 2022-03-22 06:33
Hi @adelatorreduran , thank you for your message! I actually thought just before sleep yesterday that I need to contact you for last questions before the conference :-) Is it possible to try the conference as a moderator? I mean, it is probably just zoom, but maybe there are additional things I can do as a host? E.g. mute/unmute, etc.? 

I should also probably reread the guide to organisers on your website... But the main question is above.

**Comment by adelatorreduran** [comment] 2022-03-22 15:22
@ViktoriiaKornich, I think the best option is if we give you a zoom account within our license so you can be host.

**Comment by ViktoriiaKornich** [comment] 2022-03-22 15:33
I also wonder, should we send a reminder email to all the registered participants?

**Comment by adelatorreduran** [comment] 2022-03-22 18:09
Yes, what email account would you like to use (it cannot be associated to another zoom account). And yeah, we will send it shortly.

**Comment by ViktoriiaKornich** [comment] 2022-03-22 20:31
Please, use my personal email vgkornich at gmail dot com. Thank you! I hope to receive the last title of the talk soon, and then will update the program.

**Comment by adelatorreduran** [comment] 2022-03-22 22:30
You should be getting an emaill.

**Comment by ViktoriiaKornich** [comment] 2022-03-23 11:11
Thank you, I have received it and created a zoom account. I just wonder, how other people will be able to chair sessions?

**Comment by ViktoriiaKornich** [comment] 2022-03-23 11:16
I have also put the last two titles of the talks and created a pull request.

**Comment by ViktoriiaKornich** [comment] 2022-03-23 11:19
Also, again, should we send a reminder to the registered participants? I think, it is very likely that many of them forgot about it.

**Comment by adelatorreduran** [comment] 2022-03-23 20:21
@ViktoriiaKornich you can give them host or co-host privileges. I have merged the pull request. About the email, yes you can create an issue the same way we did for the announcement email, and we will send it to the registered email accounts.

**Comment by ViktoriiaKornich** [comment] 2022-03-23 23:02
Thank you! For the announcement email, I did not create an issue, I only wrote text. I looked up and did not find out how to create it. Could you open an issue and I will write the text?

**Comment by akhmerov** [comment] 2022-03-23 23:31
Please open the issue [here](https://github.com/virtualscienceforum/virtualscienceforum/issues/new?assignees=&labels=email&template=email.md). Don't worry about making mistakes there, it won't be sent until it's approved.

**Comment by ViktoriiaKornich** [comment] 2022-03-24 12:28
Thank you! I have written text there and submitted changes. In my opinion, looks fine.

**Comment by ViktoriiaKornich** [comment] 2022-03-27 08:53
Guys, I wonder about how exactly to host the conference? People registered and received a link. I have a VSF account in zoom. How these two things should work together? I also register and somehow automatically recognised as a host if I am logged in or what?

**Comment by ViktoriiaKornich** [comment] 2022-03-27 19:11
I also wonder, if anybody from VSF with experience in hosting can be present at the beginning of the workshop just in case we mess up something with zoom?

**Comment by ViktoriiaKornich** [comment] 2022-03-27 19:11
It is scary to imagine...

**Comment by adelatorreduran** [comment] 2022-03-28 17:17
Hi @ViktoriiaKornich, if you log in on zoom with your VSF account and go to meetings, you will see the booked zoom slots for the conference under recurring sessions. When you are ready for it, click on start. 

I was planning to be there to help you start your conference, but I got additional experiment time in Chicago this week. It might be hard for me to join. It begins at 7 AM for me now, and my current sleep schedule is a bit unpredictable. I'll make sure someone from VSF is there tho, don't worry!

**Comment by ViktoriiaKornich** [comment] 2022-03-28 18:43
@adelatorreduran I have logged in and there is no booked time slot in the Meetings...

**Comment by akhmerov** [comment] 2022-03-28 18:46
Please check again: I just added you as a meeting host.

**Comment by ViktoriiaKornich** [comment] 2022-03-28 18:49
No, I logged in once more and there is nothing...

**Comment by adelatorreduran** [comment] 2022-03-28 18:52
If you are logging in on your browser, make sure to change to 'All' instead of 'Myself' on the top right corner of the meetings tab.

**Comment by adelatorreduran** [comment] 2022-03-28 18:53
![image](https://user-images.githubusercontent.com/75702068/160467025-70971a81-5b8d-4c69-add6-de3b846c64f0.png)

**Comment by ViktoriiaKornich** [comment] 2022-03-28 18:56
I cannot find this option... Let me search a bit more...

**Comment by akhmerov** [comment] 2022-03-28 18:58
What if you use the direct link: https://virtualscienceforum-org.zoom.us/meeting/89192095960 ?

**Comment by ViktoriiaKornich** [comment] 2022-03-28 18:59
Invalid meeting ID. (3,001) That is what I get

**Comment by akhmerov** [comment] 2022-03-28 19:01
:thinking: and to double-check you are logged in with your gmail account, so that the domain is https://virtualscienceforum-org.zoom.us/ ?

**Comment by ViktoriiaKornich** [comment] 2022-03-28 19:01
yes, I am logged in with that zoom account.

**Comment by adelatorreduran** [comment] 2022-03-28 19:04
I see the right meeting and I see @ViktoriiaKornich as the alternative host. This is odd...

**Comment by adelatorreduran** [comment] 2022-03-28 19:05
Try this: https://virtualscienceforum-org.zoom.us/meeting#/upcoming and then see if you see the options that I showed in that image

**Comment by ViktoriiaKornich** [comment] 2022-03-28 19:07
No, I don't have it.

**Comment by adelatorreduran** [comment] 2022-03-28 19:07
I will send you a zoom invitation to your email. We can chat there and share screen

**Comment by ViktoriiaKornich** [comment] 2022-03-28 19:08
OK, sure, although my internet is not very nice here: just moved to a new apartment. So please be patient XD

**Comment by adelatorreduran** [comment] 2022-03-28 19:09
Of course!

**Comment by ViktoriiaKornich** [comment] 2022-03-28 19:12
I joined the zoom session.

**Comment by adelatorreduran** [comment] 2022-03-28 19:12
Can you hear me?

**Comment by adelatorreduran** [comment] 2022-03-28 19:17
@akhmerov I think the issue is that @ViktoriiaKornich is only a member and not an Admin. Her options are different to ours.

**Comment by akhmerov** [comment] 2022-03-28 19:19
Can you also send me a link to your zoom meeting if it's still on so that I can take a look?

**Comment by adelatorreduran** [comment] 2022-03-28 19:21
sent

**Comment by akhmerov** [comment] 2022-03-28 22:13
OK, to summarize the discussion:

- Starting the meeting requires using the registration link, but works once the organizer is added to the meeting as an alternative host.
- During the meeting the host needs to make presenters co-hosts, disable participants from unmuting themselves, and mute everyone.
- When participants raise hand, they need to ask to be unmuted.
- At the beginning of each talk the host (or cohosts) should start a cloud recording and stop it at the end of each talk.
- It's a good idea to have an extra pair of eyes to see that everything goes OK.

**Comment by ViktoriiaKornich** [comment] 2022-03-29 10:09
Thank you! We will train everything today :-)

**Comment by ViktoriiaKornich** [comment] 2022-03-29 13:58
We trained everything with David and Alessio, and everything seems to work. Both of them should be present on both days of the workshop, so there is some safety for me, if something does not work. However, certainly, I hope that Anton will join tomorrow just in case.

**Comment by ViktoriiaKornich** [comment] 2022-03-29 14:06
Thank you!

**Comment by ViktoriiaKornich** [comment] 2022-03-31 19:02
@akhmerov @adelatorreduran @giulia-pacchioni thank you very much for your support and advice! In my opinion, it was a great event and I am not sure whether we would manage to organise it without you! I am looking forward to your future events and I wish you all the best in your endeavours!

**Comment by ViktoriiaKornich** [comment] 2022-03-31 19:02
If I can be of any help for you, please, do not hesitate to contact me!

**Comment by akhmerov** [comment] 2022-04-01 07:42
Great that you liked it and that the event was a success! Congratulations!

There are still several things that we'd like you to do. Firstly, please go over the video recordings (I'll send a link to your email) and there for each file indicate the start and end of what you want to be published. For example if you started the recording a bit earlier where the speaker didn't turn on presentation mode yet. For that please respond here with data like:

```
day 1
Recording 1: start 00:00:23 end 43:01:21
...
```

Please also double-check that the speakers are OK with publishing the recordings.

Once this is done, we'll publish the recordings to youtube, include them in the workshop page. Then I recommend writing another email announcement to the participants to let them know that the recordings are online.

Finally, please think of any feedback that you have for us, be it positive, negative, or suggestions for something new and share here.

**Comment by ViktoriiaKornich** [comment] 2022-04-01 10:16
Thank you! I have written to all the speakers, and have already received several feedbacks. So far the majority of people agree to publish. Some of them have questions. 1) One presenter showed unpublished data, so she wants her talk to be put online later, when everything is published. Is it possible? 2) One presenter wants to check the recording. Is it possible? 3) One presenter agrees, but asks whether we need a signed document with his consent?

**Comment by akhmerov** [comment] 2022-04-01 10:24
> One presenter showed unpublished data, so she wants her talk to be put online later, when everything is published. Is it possible?

Yes, certainly. Let us know which video should be published later.

> One presenter wants to check the recording. Is it possible?

Yes, please go ahead and share the recording link with the speaker.

> One presenter agrees, but asks whether we need a signed document with his consent?

No need to sign; just stating the agreement is fine.

**Comment by ViktoriiaKornich** [comment] 2022-04-01 10:47
Thank you very much! I received more replies, but the problem is that some of them say that they agree to put the talk on the conference website. Even though I wrote about conference website AND youtube. Should I ask them again separately about youtube?

**Comment by akhmerov** [comment] 2022-04-01 10:51
I think it's fine as is.

**Comment by ViktoriiaKornich** [comment] 2022-04-01 10:53
OK, good, then I will wait until I receive all replies and then will let you know about everything together.

**Comment by ViktoriiaKornich** [comment] 2022-04-07 13:26
I am ready to provide the information regarding recordings. All speakers agreed to upload their recordings online, except: 

1) Sofia Michaela Souliou (third speaker on day 1) asked to upload her video after all presented data is published. Certainly, we do not know, when it will happen, but if possible, please, just save her talk for some time. I will indicate the beginning and end of her recording below, but please *do not upload it yet*.

2) Amir Yacoby (fifth speaker on day 1) has not responded yet. I will indicate the beginning and end of his talk below, but please *do not upload it yet*. If possible, please, save it for some time.

Please, see below the beginning and end limits for the recordings:

day 1
Recording 1:   start    00:00:23    end   00:42:43
Recording 2:   start    00:00:13    end   00:46:51
Recording 3:   start    00:00:36    end   00:40:24
Recording 4:   start    00:00:31    end   00:41:36
Recording 5:   start    00:00:00    end   00:42:07
Recording 6:   start    00:00:20    end   00:15:49
Recording 7:   start    00:00:32    end   00:18:02
Recording 8:   start    00:00:13    end   00:18:40

day 2
Recording 1:   start    00:00:00    end   00:42:10
Recording 2:   start    00:00:12    end   00:48:35
Recording 3:   start    00:00:00    end   00:37:35
Recording 4:   start    00:00:41    end   00:40:19
Recording 5:   start    00:00:39    end   00:15:50
Recording 6:   start    00:00:00    end   00:15:31
Recording 7:   start    00:00:27    end   00:12:47
Recording 8:   start    00:00:00    end   00:14:50
Recording 9:   start    00:00:00    end   00:14:08      

Please, do not forget *not* to upload Recordings 3 and 5 from day 1. If possible, please, save them for some time. If it is not possible, please, let me know about it.

Thank you very much!

**Comment by ViktoriiaKornich** [comment] 2022-04-11 10:05
@akhmerov @adelatorreduran @giulia-pacchioni I am receiving requests for the videos... I certainly understand, that you are all busy, but maybe something can be done to speed the process up? E.g. I can do part of the work, if you let me know, how. Or I can work with somebody else from VSF, who has more time.

**Comment by akhmerov** [comment] 2022-04-11 11:21
I'll get to those soon, give me a couple of days—we've an exam period and other deadlines.

**Comment by ViktoriiaKornich** [comment] 2022-04-11 11:30
Sure, thank you very much! I would not remind if no inquiries for recordings. If I can do any part of work, please, let me know.

**Comment by akhmerov** [comment] 2022-04-16 17:24
I've published the videos. The two remaining ones for which no permission is granted are now private on youtube, so it should be straightforward to update as soon as the speakers grant permissions. Would you like to write an email to the workshop registrants informing them that the videos are published? Once again, you can do so by using [this link](https://github.com/virtualscienceforum/virtualscienceforum/issues/new?assignees=&labels=email&template=email.md) and then we'll edit it appropriately.

**Comment by akhmerov** [comment] 2022-04-16 17:30
Please also let me know if there's something to fix with the videos—it's straightforward to do and we still have the originals.

**Comment by ViktoriiaKornich** [comment] 2022-04-16 17:42
Thank you very much! I thought, you have already forgotten! I wonder, if the names of the speakers can be put into the video titles for all videos? The majority of them have the names of the speakers, so I think it would be nice to put the names for the others too. If you have troubles identifying which talk it was, please, let me know! I will write the draft of the letter for the registered participants about the videos online.

**Comment by akhmerov** [comment] 2022-04-16 17:53
Youtube limits the title to 100 characters, that's why talks with longer titles have the speaker name in the video description. If you have alternative video titles shorter than 100 characters—let me know and I'll update those.

**Comment by ViktoriiaKornich** [comment] 2022-04-16 17:55
I see, I did not know that. Anyway, there are names on the webpage. I am finishing with the draft now :-)

**Comment by ViktoriiaKornich** [comment] 2022-04-16 18:04
Strange, I have written the text, but now, after submission of the issue, I don't see it... Hopefully, you can see it.

**Comment by ViktoriiaKornich** [comment] 2022-04-16 18:15
I have checked the videos, and everything seems to be good, thank you! I will send the links to the speakers separately from the general email, and ask if they are fine with it. Although, some of them have already seen the recordings.

**Comment by akhmerov** [comment] 2022-04-16 18:22
Sounds good. I'll close this issue to mark that there are no pending actions from our side, but do reply here once you hear from the two remaining speakers that their videos may be made public.

**Comment by ViktoriiaKornich** [comment] 2022-04-16 18:23
OK, thank you!

**Closed by akhmerov** 2022-04-16 18:22 UTC
Labels: approved, session

**Comment by ViktoriiaKornich** [comment] 2022-04-18 07:29
@akhmerov Amir replied and agreed to post his talk online. Regarding Michaela, if it happens, it will not be any time soon, as far as I understand.

**Comment by akhmerov** [comment] 2022-04-18 07:35
Thanks, I published Amir's talk now.

**Comment by ViktoriiaKornich** [comment] 2022-04-18 07:39
Thank you very much! Now, it is really closed :-)
