### ISSUE TITLE
Proposed workshop: Does condensed matter physics need to worry about a replication crisis?

### ISSUE THREAD

**Issue by brianqskinner** [virtualscienceforum/virtualscienceforum#578] opened 2023-01-07 15:32 UTC
## Organizers

**List the names of the organizers, preferably [link](url) to their personal webpages.**
Brian Skinner [link](https://physics.osu.edu/people/skinner.352) and Sergey Frolov [link](https://www.physicsandastronomy.pitt.edu/people/sergey-frolov)

## Description

During the last decade, the social and biomedical sciences have been grappling with a “replication crisis,” in which a large fraction of published results cannot be verified or reproduced. The causes and solutions to this replication crisis are still not entirely clear, but generally its roots involve publication bias, the predominance of trendy research narratives, and unreliable or fraudulent manipulation of data.  

Condensed matter physics, as a field, has largely been considered immune to replication crises by its practitioners, since its experiments tend to be data-rich as compared to those in the social or medical sciences. But many of the same root problems are also prevalent in condensed matter, so it is both reasonable and timely to consider the questions: do we need to worry about a replication crisis coming for us? Is it already here?

In this short workshop we will review the replication crisis as it has arisen in the social and medical sciences, then consider a few case studies of prominent recent results in condensed matter that have proven unreliable, and close with a panel discussion.

## List of potential speakers 

**Please have more potential speaks than slots in the conference: people are often busy.**
David Abergel, Piet Brouwer, Jean-Sebastien Caux, Tomasz Durakiewicz, Paul Ginsparg, David Goldhaber-Gordon, Benjamin Heinrich, Peter Hirschfield, Gil Kalai, Patrick Lee, Igor Mazin, Silvia Milana, Laurens Molenkamp, Kathryn Moler, Vincent Mourik, David Muller, Hal Pashler, Seth Putterman, Andrea Taroni, Jessica Thomas, Dirk van der Marel, Simine Vazire, Karl Ziemelis

## Preferred date and time slot

Thursday, March 2, 2023, 17:00 – 20:00 UTC  (12:00 – 15:00 EST)

## Additional remarks (if any)

The workshop will comprise three talks (30 min + 15 min Q&A) and one panel discussion with ~6 panelists.

We will also invite contributed talks from a certain set of invited participants, which can be posted to the workshop website.

**Comment by giulia-pacchioni** [comment] 2023-01-10 03:44
Hi Brian and Sergey,

Very interesting initiative! I have one minor suggestion: I can see you list several Nature editors among the potential speakers -- ideally, I think it would be interesting to hear opinions coming from different publishers, as the policies and approaches can be slightly different. For example, you could add Sami Mitra from PRL and Jelena Stajic from Science to your list. 

I'm looking forward to the event!
Best wishes,
Giulia

**Comment by brianqskinner** [comment] 2023-01-19 00:08
Hi Anton,

Thanks, I very much appreciate your help with getting this going. We have
in mind only a small and limited workshop program, but I'm still relatively
excited to see what comes of it.


>    - The workshop title is a "yes/no" question, which is both relatively
>    narrow and vague: I expect that most would agree that there's a replication
>    problem to some extent, which only leaves open a question "what to label as
>    a crisis". I suggest to consider a title that would imply more than
>    quantifying a hard to define problem.
>
> I agree that the workshop title right now isn't ideal. I like the idea of
specifically framing the workshop as a comparison to the "replication
crisis" in other fields. At the moment I can't think of a better way to
express this in the title. It could be something like "To what extent is
there a replication crisis in condensed matter?", but that also seems not
ideal.
Sergey, any suggestions?

>
>    - The workshop plan has "a few case studies of prominent recent
>    results in condensed matter that have proven unreliable". I wonder whether
>    this helps address the workshop question: I believe people started talking
>    about a *reproducibility crisis* in other fields after a large scale
>    replication study found a problem. A few results, even prominent, unlikely
>    form a comparably strong evidence for a systemic problem. Can you elaborate
>    on that?
>
> This seems to me like kind of an intrinsic limitation of a short workshop.
We want to keep this quite short -- just one day, 3 hours total. That
leaves room for 3 talks and one panel discussion. So I think that one talk
giving an overview of the replication crisis and two talks discussing
reproducibility issues, in a broad sense, in two specific subfields. (Right
now we have talks lined up about Majoranas and about high-pressure
superconductivity.) Then the panel discussion will try to cover larger meta
issues.
Of course, if I knew of any meta-level studies about the reproducibility of
condensed matter results in general then we would certainly include them.
But I sort of see this workshop as only the beginning of a much-needed
conversation.

-BrianMessage ID:
***@***.***>

>

**Comment by brianqskinner** [comment] 2023-01-19 00:42
Well Anton, if Delft turned out the data we asked for, we could have a
larger study, you know.

On Wed, Jan 18, 2023 at 7:08 PM Brian Skinner ***@***.***>
wrote:

> Hi Anton,
>
> Thanks, I very much appreciate your help with getting this going. We have
> in mind only a small and limited workshop program, but I'm still relatively
> excited to see what comes of it.
>
>
>>    - The workshop title is a "yes/no" question, which is both relatively
>>    narrow and vague: I expect that most would agree that there's a replication
>>    problem to some extent, which only leaves open a question "what to label as
>>    a crisis". I suggest to consider a title that would imply more than
>>    quantifying a hard to define problem.
>>
>> I agree that the workshop title right now isn't ideal. I like the idea of
> specifically framing the workshop as a comparison to the "replication
> crisis" in other fields. At the moment I can't think of a better way to
> express this in the title. It could be something like "To what extent is
> there a replication crisis in condensed matter?", but that also seems not
> ideal.
> Sergey, any suggestions?
>
>>
>>    - The workshop plan has "a few case studies of prominent recent
>>    results in condensed matter that have proven unreliable". I wonder whether
>>    this helps address the workshop question: I believe people started talking
>>    about a *reproducibility crisis* in other fields after a large scale
>>    replication study found a problem. A few results, even prominent, unlikely
>>    form a comparably strong evidence for a systemic problem. Can you elaborate
>>    on that?
>>
>> This seems to me like kind of an intrinsic limitation of a short
> workshop. We want to keep this quite short -- just one day, 3 hours total.
> That leaves room for 3 talks and one panel discussion. So I think that one
> talk giving an overview of the replication crisis and two talks discussing
> reproducibility issues, in a broad sense, in two specific subfields. (Right
> now we have talks lined up about Majoranas and about high-pressure
> superconductivity.) Then the panel discussion will try to cover larger meta
> issues.
> Of course, if I knew of any meta-level studies about the reproducibility
> of condensed matter results in general then we would certainly include
> them. But I sort of see this workshop as only the beginning of a
> much-needed conversation.
>
> -BrianMessage ID:
> ***@***.***>
>
>>

-- 
Prof. Sergey Frolov
Department of Physics and Astronomy
University of Pittsburgh
3941 O’Hara Street
Pittsburgh, PA, 15260, USA
***@***.***
http://frolovlab.org/

**Comment by akhmerov** [comment] 2023-01-19 01:15
@brianqskinner forwarding github emails makes the replies [appear](https://github.com/virtualscienceforum/virtualscienceforum/issues/578#issuecomment-1396293975) on github as if comments were made by you. Replies on github will also not be forwarded to Sergey unless he actually follows this issue via github. Therefore if Sergey wants to take part in discussion, it is best if he uses an own github account to respond or views this issue online and communicates via you.

**Comment by akhmerov** [comment] 2023-01-20 14:15
I think the idea of contrasting with other fields is great! On option for the title that would make it more open ended could be "replication crisis in condensed matter physics"—the description can of course still include the "does it apply" question. Or if you want to focus on the contrast, then something like "how is replication crisis in condmat different?"/"specifics of replication crisis in condmat" might work.

https://www.nature.com/articles/533452a seems to suggest that the existence of replication problems in physics is not too controversial of claim.

I've found the [Wiki page](https://en.wikipedia.org/wiki/Replication_crisis) illuminating, in particular the part describing what kinds of replication one considers. In relation to that I observe that as far as I am aware the two cases that you list concern lacking reproducibility: being able to come to the same conclusions based on the same data. On the other hand, different levels of replication may also be interesting, especially the "conceptual replication"—when the same hypothesis is tested using a different procedure. A recent preprint https://arxiv.org/abs/2301.03838 can be considered a failed conceptual replication, but there are also multiple examples of effectively failed replications in Majorana field. The "inverse Occam's razor" is also a sharp viewpoint that fits in the scope of low conceptual replicability and I see that you listed its author among the potential speakers.

The above are merely points for your consideration, let me know what you think.

Separately from that, in order to keep the discourse civil I would like to ask you to make it clear to the presenters and the panelists that they should avoid commenting about people and rather focus on the objective matter of the attempted reproductions. I absolutely expect that this will be the case, but given that the matter is sensitive I believe an extra warning is appropriate.

Do you agree?

Finally as the next steps:
- [ ] I'll prepare a draft workshop page that you can tweak and edit.
- [ ] You may start approaching the potential speakers and panelists. At this point the specific date and time slot is still flexible, but please keep me in the loop if you want to change it.

**Comment by brianqskinner** [comment] 2023-01-21 02:36
Hi Anton,

Thanks for your suggestions and comments. Indeed we will try to discuss the
replication problem at different levels, but in the end our role as
organizers is mostly to invite interesting people and not to dictate the
content of their talks. But we'll certainly keep in mind some of these
questions when we prepare suggested questions and topics for the panel to
discuss.

Regarding the title, after going back and forth a bunch, Sergey and I are
of the opinion that we should just stick with the original title "Does
condensed matter physics need to worry about a replication crisis?" There
are a couple things that are suboptimal about this title, of course (it's
long and unwieldy and falsely suggests a binary question). But other
options seem to have worse problems ("the replication crisis in condensed
matter" sounds alarmist, and like we are making a strong claim already
about the problem; something like "implications of the replication crisis
for condensed matter" has similar problems, and our ideal attendee might
not know what the replication crisis is; etc). So let's please stick with
the originally suggested title.

Regarding this comment:

I would like to ask you to make it clear to the presenters and the
> panelists that they should avoid commenting about people and rather focus
> on the objective matter of the attempted reproductions
>

We certainly agree with you that the focus should be on the science and on
the larger issues that lead to non-replicable research in condensed matter
and its subfields. We absolutely don't want the focus to be on criticizing
specific people. But at the same time, I want to be clear about what we, as
organizers, can guarantee. Our intention is to invite certain speakers and
panelists who we think have a valuable perspective on the issues we care
about: the replication crisis in other fields, the appearance of unreliable
research results in condensed matter, and the factors that lead to it in
each case.  We will explain to the speakers our intended focus for the
workshop and then give them broad freedom to choose the content of their
talks. I think this will lead to good talks in the sense that both you and
I have in mind. But I don't think it makes sense to tell anyone "you can
talk about how there was a problem with X paper, but you cannot name the
authors of the paper."

Like you, I don't expect there to be any problem. We are being circumspect
about who we invite as speakers and panelists (you can see our list of
potential speakers and panelists in the application), and no one is going
to want to be offensive. (Also, to be clear, neither Sergey nor I will give
a talk or participate in the panel.) And either I or the panel moderator
will certainly make sure to provide moderation in the event that any
discussion is starting to seem defamatory.

Is this enough of a guarantee for you? If you feel uncomfortable about it
or if you feel like it is inappropriate for VSF, then we can withdraw our
application and host the workshop independently. Although we would
certainly prefer to continue to host it through VSF.

If everything looks okay to you, then please proceed to make a draft of the
workshop page and we will invite speakers and panelists.

Thank you,
Brian

**Comment by akhmerov** [comment] 2023-01-21 19:36
Hi @brianqskinner,

Thank you for considering my suggestions.

> >  I would like to ask you to make it clear to the presenters and the
 panelists that they should avoid commenting about people and rather focus
 on the objective matter of the attempted reproductions
>
> ...
> But I don't think it makes sense to tell anyone "you can
talk about how there was a problem with X paper, but you cannot name the
authors of the paper."

After rereading what I wrote, I realize that my formulation was very imprecise and overly broad, my apologies for that.

It is definitely appropriate to name the authors, and to make factual statements about what happened e.g. when describing the process of obtaining the data or otherwise communicating with the authors. On the other hand, describing people's implied qualifications or motivation would go against the VSF code of conduct, even if clearly declared as a personal opinion and therefore not amounting to a defamation.

To make a concrete positive example, the fireside chat Sergey and Vincent ran about their analysis of the Majorana works would meet the VSF standard of conduct.

Does this sound reasonable?

I also invite the other members of @virtualscienceforum/core to comment if my interpretation of our code of conduct is inaccurate.

**Comment by sentefmi** [comment] 2023-01-21 20:02
Hi @akhmerov and @brianqskinner, this clearly sounds like an interesting meeting.

Regarding the code of conduct: You anyway need to point speakers and audience to the attendee guide https://virtualscienceforum.org/attendeeguide/ -- and ask them to be professional, polite, and respectful. At the end I suppose it is your (and our) call to decide which behavior falls under that category, and where the boundary is. To me it seems difficult to define that a priori without having specific behavior/actions to judge.

Does that make sense? I would trust your professional judgment here.

**Comment by brianqskinner** [comment] 2023-01-21 20:34
Hi @akhmerov and @sentefmi. Thanks for the clarifications. It looks like we
are not in any danger of running afoul of your advice, and I am happy to
agree to give a reminder to our speakers of the kind that you mentioned.

Please proceed with making the draft workshop website whenever you are
ready.

Thanks,
Brian

**Comment by brianqskinner** [comment] 2023-02-02 16:02
Hi @akhmerov and others. Today we are one month away from this workshop,
and we have all our speakers and panelists lined up.

Is there a draft of the workshop website yet? We would like to start
advertising the event.

Thanks,
Brian

**Comment by akhmerov** [comment] 2023-02-02 16:31
@brianqskinner the pull request for the workshop is in #583, preview [here](https://virtualscienceforum.org/pr-583/) (don't advertise this link). To propose edits use [this link](https://github.com/virtualscienceforum/virtualscienceforum/edit/repro_workshop/src/reproducibility_in_cmp.md?pr=%2Fvirtualscienceforum%2Fvirtualscienceforum%2Fpull%2F583) or just comment in #583.

The things that I would like from you are:
- The workshop program
- Whether you and Sergey want an `@virtualscienceforum.org` email for contacts from workshop participants, and if yes which handle would you want.
- A draft email announcement to be sent to the VSF mailing list. For that [create a new issue](https://github.com/virtualscienceforum/virtualscienceforum/issues/new?assignees=&labels=email&template=email.md) and follow the descriptions in the template.
- Confirm whether the short workshop title ("reproducibility crisis in condensed matter") on the main page is OK. The full title is a mouthful, so I came up with a shortened version, while the workshop page has the full title.

---
I will also create a zoom meeting and add the registration form in a bit.

**Comment by brianqskinner** [comment] 2023-02-02 19:42
Hi Anton,

Thank you for putting this together. I made a few small suggested
alterations (typo corrections) in the comments to #583.

In response to your questions:

The workshop program is:

   - 12:00 - 12:05, Welcome and Introduction
   - 12:05 - 12:45, Simine Vazire (University of Melbourne)
   - 12:45 - 1:25, James Hamlin (University of Florida)
   - 1:25 - 2:05, Vincent Mourik (Forschungszentrum Jülich)
   - 2:05 - 3:00, panel discussion
      - David Muller (Cornell University)
      - Igor Mazin (George Mason University)
      - Jessica Thomas (Physical Review)
      - Eugenie Reich (Pollock Cohen LLP)
      - Laurens Molenkamp (University of Würzburg)

(We don't have titles yet for the talk: I will get them soon)

I don't think that Sergey and I need a separate email address at @
virtualscienceforum.org. Since our contact information is listed at the
bottom of the page it will be easy for people to contact us in the usual
way.

The shortened workshop title is okay.

I will draft an email announcement later today.

Thanks,
Brian

**Comment by akhmerov** [comment] 2023-02-06 17:29
OK, the page and the registration are live at https://virtualscienceforum.org/reproducibility_in_cmp/ (take care—this is the final URL; you've used the test URL before) and the workshop is announced to the mailing list. Once you have the talk titles for me, let me know. Additionally, I advice to register the speakers for the workshop yourself (using their emails)—otherwise the speakers sometimes forget.

**Comment by brianqskinner** [comment] 2023-02-07 14:44
Hi Anton,

I have the talk titles now. Would you please add them to the program?

Simine Vazhire (University of Melbourne): "What is a replication crisis and
how do I know if I'm in one? Lessons from Psychology"

James Hamlin (University of Florida): "Extracting data from scientific
publications"

Vincent Mourik (Forschungszentrum Jülich): "Non reproducible claims in
Majorana research"

Thank you!

-Brian

**Comment by akhmerov** [comment] 2023-02-08 10:18
Done now, and I watch both this issue as well as the pull request. Closer to the event we'll need to send a reminder email to the registered participants.

**Comment by brianqskinner** [comment] 2023-02-15 16:46
Hi Anton,

Sergey and I would like to include some pre-recorded talks in the workshop.
Are you okay with embedding these talks in the workshop web page?

Our plan is to issue a fairly broad invitation to suggest a pre-recorded
talk that is in line with the workshop topics. Sergey and I will then
review the suggested talks (title, speaker, and description) before
agreeing to include them. Speakers will be encouraged to pre-record their
talks through the Speakers' Corner, but we will also accept a link to a
self-uploaded youtube video or a video file sent to us directly. (We can
make our own special youtube channel for the event, or, if you prefer, send
them to you to upload through VSF.)

We are hoping to embed the pre-recorded talks on the web page, in the same
way that we did for the Quantum Oscillations workshop.
I just wanted to check with you that you are okay with this plan before we
start issuing invitations.

Thanks,
Brian

**Comment by akhmerov** [comment] 2023-02-15 18:49
All sounds good. Some practical remarks:

- The same standard of conduct applies also to the contributed talks
- Speakers' corner talks must be scheduled at least 1 full week in advance due to the announcements, and therefore Sunday is a deadline for the Speakers' corner talks of the week of the workshop.
- Speakers' corner is primarily designed for original research, but other types of talks may fit as well (e.g. there was a talk by JS Caux about SciPost).

**Comment by brianqskinner** [comment] 2023-02-15 20:07
Got it, thanks. We will start issuing invitations.

**Comment by brianqskinner** [comment] 2023-02-22 18:16
Hi Anton,

We are starting to receive contributions for the "Pre-recorded Talks"
section of our workshop. The first such talk has been sent to us as a
recording by Dirk van der Marel at University of Geneva. You can find a
copy of it here:
https://drive.google.com/drive/folders/1ylsDlHrGC6uNvKjgxqvKtE7NgIUfZL7V?usp=sharing

Would you mind uploading this talk to the VSF youtube channel and embedding
it on the workshop page?
The title of the talk is "Room-temperature superconductivity - or not?"

Perhaps we can add a section to the workshop web page, just below the main
program, with "Pre-Recorded Talks". There will be perhaps four more added
during the next week.

Thanks,
Brian

**Comment by akhmerov** [comment] 2023-02-26 19:22
Hey Brian, just returning from a trip. I've uploaded the talks to youtube, but I need speaker names, affiliations, talk titles and descriptions to publish them. Can you please provide them? Also let's plan to send the workshop registration reminder tomorrow, so that you can:
- Announce that the talks are published (I think there would be enough time to take care of that).
- Announce the related Speakers' Corner talk
Would you like to draft the reminder email?

**Comment by brianqskinner** [comment] 2023-02-27 04:18
Hi Anton,

Thanks. Below are the information you requested for the two uploaded talks,
as provided by the speakers.

Dirk van der Marel, DPMQ,  University of Geneva

*Room-temperature superconductivity - or not?*

Physics is about phenomena that can be reproduced under identical
conditions. For this to be possible it is of crucial importance that
scientific publications provide an accurate description of the methods of
data acquisition and analysis, and of the data themselves. The issues
pointed out below illustrate the importance of accurate reporting.

In 2020 a publication in Nature (meanwhile retracted) announced the
discovery of room-temperature superconductivity in a carbonaceous sulfur
hydride (CSH). The evidence for superconductivity was from resistivity and
magnetic susceptibility measurements. In the figures showing the
susceptibility, chi(T) , "the background signal, determined from a
non-superconducting CSH sample at 108 GPa, has been subtracted from the
data" according to the description provided in the paper. The thus
corrected susceptibility at 160 GPa (open data posted on arXiv), when
displayed on an enlarged scale, exhibits a remarkable sawtooth profile
which is composed of two components: chi(T) = q(T)+P(T). Here q(T) consists
of integer multiples of q0 = 0.16555 nV and P(T) is a 15-node cubic spline
with normal boundary conditions. These remarkable features are a shared
property of the published background-corrected susceptibility data for all
6 reported pressures, however, since the160 GPa data has the biggest q0 it
was noticed first for those data. Other than that, the background corrected
data are completely noise-free, to the point that even the third
temperature derivative of the 160 GPa data is still a smooth function. The
underlying raw data (also posted on arXiv) contain considerable noise, as
expected for experimental data.
In later communications some of the authors have claimed that they did not
subtract a background signal at a different pressure, but used a different
methodology to obtain the background corrected signal from the underlying
raw data. While it is not clear how this could lead to the pathological
features q(T)+P(T), it is interesting that for all 6 reported pressures a
correlation analysis of the raw data indicates that those raw data also
contain the steps of size q0 at the same temperatures as the background
corrected data.


Yifan Jiang, University of Pittsburgh

*Hysteretic Supercurrents and Zero-bias Peaks in Semiconductor Nanowire
Devices with Micromagnets*

Many experiments for searching Majorana bound states are based on
semiconductor nanowire devices. A typical device has the structure of a
superconductor-semiconductor-superconductor junction or a
superconductor-semiconductor junction. Zero-bias peaks of conductance from
these devices are considered as signatures of Majorana bound states. In our
experiments, we fabricate Sn-InSb-Sn junction devices and Al-InAs junction
devices. Micromagnets are deposited close to these junctions to provide
local magnetic fields. Hysteretic supercurrents are observed in Sn-InSb-Sn
junctions, confirming the effectiveness of micromagnets. In Al-InAs
junctions, we observe zero-bias peaks under zero external applied magnetic
field. Especially, we demonstrate visually long zero-bias peaks and the
peaks are hysteretic under magnetic field scans. The origin of these
zero-bias peaks is likely from trivial Andreev bound states and there is no
strong evidence that Majorana bound states are responsible for energy
states observed in the experiments.

We will likely have one more pre-recorded talk uploaded to that same file
within a day or two.

We would also like to add two more talks to the "Pre-Recorded Talks"
section. As follows:

Michael B. Weissman, University of Illinois at Urbana-Champaign

[Michael is giving his talk via the Speakers' Corner on Tuesday. Please
embed his talk on the workshop webpage as soon as it is available.
The information is the same as here:
https://virtualscienceforum.org/speakers-corner/#erroneous-statistics-in-physical-review-physics-education-research
]

Anatoli Polkovnikov, Boston University

*Is there any evidence for Many-Body Localization?*

I will introduce the notion of the adiabatic gauge potential as a generator
of continuous adiabatic transformations and how we can use its norm (aka
fidelity susceptibility or the quantum geometric tensor) as a probe
distinguishing chaotic and integrable systems. I will discuss applications
of this probe to disordered systems and give an evidence that there is no
true many body localization in the thermodynamic limit.

[Anatoli has requested to contribute a talk that has already been recorded
and posted to youtube. Please embed this youtube link, which has a time
stamp 45:13: https://www.youtube.com/live/Rl_Wb2DZyvI?feature=share&t=2713]

I will send a draft of the reminder email in a moment, as part of a
separate message.

-Brian

**Comment by brianqskinner** [comment] 2023-02-27 04:40
Hi Anton,

Below is some suggested text for a reminder email:

Dear %recipient_name%,



We are looking forward to your participation in the upcoming workshop,
"Does condensed matter physics need to worry about a replication crisis?",
which is taking place this Thursday, March 2.

Since our original announcement, we have added an additional section of
"Pre-Recorded Talks" contributed by workshop attendees, which are now
hosted on the [web page](
https://virtualscienceforum.org/reproducibility_in_cmp/). (A few more talks
will be added in the last few days prior to the workshop.)

We strongly encourage you to take a few moments to look through the
Pre-Recorded Talks in the days before the workshop begins. Some of these
talks are related to the presentations that will be given on Thursday and
will be relevant for our discussions.

Thank you, and we look forward to seeing you at the workshop.

Thank you,
the organizers: Brian Skinner and Sergey Frolov

I think this probably looks good to send as soon as the "Pre-Recorded
Talks" section has been posted.

Thanks,
Brian

**Comment by brianqskinner** [comment] 2023-02-28 03:38
One more addition to the "Satellite Talks":

*Chiral Majorana Modes in Quantum Anomalous Hall Insulators*

*Morteza Kayyalha*

https://www.youtube.com/watch?v=jSern0eUQB4

Thanks,
Brian

**Comment by brianqskinner** [comment] 2023-03-01 18:25
Hi Anton,

One more reminder to please post the talk by Morteza Kayyalha (Penn State)
and the Speakers' Corner talk by Michael Weissman in anticipation of the
workshop tomorrow.

Thanks again for all your help. Sergey and I are both excited for the
workshop and we expect it to be full of energy and enthusiasm.

-Brian

**Comment by akhmerov** [comment] 2023-03-01 21:42
I've added both talks now.

**Comment by akhmerov** [comment] 2023-03-01 21:44
I've also now made your VSF account (associated with your gmail) a meeting host.

**Comment by brianqskinner** [comment] 2023-03-03 03:04
Hi Anton,

I thought that the workshop today went very well; thank you for all your
help!

Sergey recorded the entire workshop, and it only occurred to me after the
talk that perhaps I (as the host) should make my own recording. I'm not
sure which version you have access to through the VSF account. But just in
case there is a complete recording here of the entire event here:
https://drive.google.com/file/d/1pKCiaHrg60uLHavuXoxG4ACfJCQuW2il/view?usp=share_link

There is also a late addition to the "satellite talks":
https://drive.google.com/file/d/18wNpcMKzBckR_9epybe3-AGexwJ1EzbA/view?usp=share_link

*Supercurrent interference in few mode nanowire Josephson junctions*

*Kun Zuo, University of Sydney*

Sorry to keep dumping things on you, but this should be the last of it. I
appreciate all your work in making this workshop a success!

-Brian

**Comment by brianqskinner** [comment] 2023-03-08 20:50
Hi Anton,

Due to the recent news about another claim of room-temperature
superconductivity in the hydrides, there is suddenly a great demand to see
the recording of our workshop.

I understand that you're busy, and I don't want to leave all the burden on
you. Is it okay if Sergey or I post the video on youtube ourselves? (At
least of James Hamlin's talk?) We would really like to have it up by the
end of the day if possible.

Thanks again, and sorry for the sudden pressure.

-Brian

**Comment by akhmerov** [comment] 2023-03-08 22:23
Hey Brian; apologies for the delay—an intense period here. I'm available to publish the recordings. Can you please provide:
- The timestamps for the start and the end of each video
- The titles and descriptions if different from what's in the program

**Comment by akhmerov** [comment] 2023-03-08 22:23
Ah, also: I'll be able to publish the videos tomorrow or within a day from having the timestamps & other info.

**Comment by akhmerov** [comment] 2023-03-09 23:36
I've uploaded the videos and updated the workshop page. It will still take a couple of hours until youtube finishes processing them. Let me know if everything looks alright and if there are further follow-up actions, e.g. a post-workshop email to the participants.

**Comment by brianqskinner** [comment] 2023-03-10 00:22
Hi Anton,

I can see now that all talks have appeared on the VSF youtube channel and
are embedded on the web page. Thank you!

I think it would be nice to send one more email to workshop participants
notifying them that the recordings are posted. Here's an email you can send:

Dear %recipient_name%,



The talks and panel discussion from last week's workshop, "Does condensed
matter physics need to worry about a replication crisis?", have now been
posted publicly on the [web page](
https://virtualscienceforum.org/reproducibility_in_cmp/) and on the
[youtube ***@***.***/videos) of
the Virtual Science Forum.

Please feel free to forward the video links to anyone who might be
interested.

Thank you all for your interest and participation.

-the organizers: Brian Skinner and Sergey Frolov

Once that's done, I think we can consider the workshop concluded!

Thanks again for everything.

-Brian

**Comment by akhmerov** [comment] 2023-03-10 09:44
Done. I believe this concludes the workshop activities, and therefore I'm closing this tracking issue. Do let me know there are any other pending actions. I'm happy that the workshop was successful and timely. And of course that you ran it via VSF :)

**Closed by akhmerov** 2023-03-10 09:44 UTC
Labels: approved, session
